# Generated by Django 6.0.6 on 2026-07-12 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('nom', models.CharField(default='', max_length=200)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisations',
                'db_table': 'organisations',
            },
        ),
        migrations.CreateModel(
            name='ParametresApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_devise', models.CharField(default='FCFA', max_length=16)),
                ('rafraichissement_auto', models.BooleanField(default=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='comptes.organisation')),
            ],
            options={
                'verbose_name': 'paramètres application',
                'verbose_name_plural': 'paramètres application',
                'db_table': 'parametres_app',
            },
        ),
        migrations.CreateModel(
            name='ProfilEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=120)),
                ('adresse', models.TextField(blank=True, default='')),
                ('telephone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=80)),
                ('site_web', models.CharField(blank=True, default='', max_length=120)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to='comptes.organisation')),
            ],
            options={
                'verbose_name': 'profil entreprise',
                'verbose_name_plural': 'profils entreprise',
                'db_table': 'profils_entreprise',
            },
        ),
        migrations.CreateModel(
            name='MembreOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('proprietaire', 'Propriétaire'), ('admin', 'Administrateur'), ('membre', 'Membre')], default='proprietaire', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres_organisations', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='comptes.organisation')),
            ],
            options={
                'verbose_name': 'membre organisation',
                'verbose_name_plural': 'membres organisation',
                'db_table': 'membres_organisation',
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'organisation'), name='uniq_membre_utilisateur_organisation')],
            },
        ),
    ]
