# Generated by Django 6.0.6 on 2026-07-12 01:56

from django.db import migrations, models


def migrer_profils_vers_organisation(apps, schema_editor):
    Organisation = apps.get_model('comptes', 'Organisation')
    ProfilEntreprise = apps.get_model('comptes', 'ProfilEntreprise')
    ParametresApp = apps.get_model('comptes', 'ParametresApp')

    for org in Organisation.objects.all():
        profil = ProfilEntreprise.objects.filter(organisation_id=org.id).first()
        params = ParametresApp.objects.filter(organisation_id=org.id).first()
        changed = False
        if profil:
            if profil.nom:
                org.nom = profil.nom
            org.telephone = profil.telephone or ''
            org.email = profil.email or ''
            org.adresse = profil.adresse or ''
            org.site_web = profil.site_web or ''
            changed = True
        if params:
            org.libelle_devise = params.libelle_devise or 'FCFA'
            org.rafraichissement_auto = params.rafraichissement_auto
            changed = True
        if changed:
            org.save()


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membreorganisation',
            name='login_legacy',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='organisation',
            name='adresse',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organisation',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='organisation',
            name='libelle_devise',
            field=models.CharField(default='FCFA', max_length=16),
        ),
        migrations.AddField(
            model_name='organisation',
            name='modifie_le',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='rafraichissement_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='site_web',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='organisation',
            name='telephone',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.RunPython(migrer_profils_vers_organisation, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='ParametresApp',
        ),
        migrations.DeleteModel(
            name='ProfilEntreprise',
        ),
    ]
