# Generated by Django 6.0.6 on 2026-07-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_fusion_organisation_et_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='sync_seq',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
