# Generated by Django 6.0.6 on 2026-08-12 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0014_chargeplateforme_nature_recurrent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesBackoffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('actif', models.BooleanField(db_index=True, default=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acces_backoffice_ajoutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'accès backoffice',
                'verbose_name_plural': 'accès backoffice',
                'db_table': 'acces_backoffice',
                'ordering': ['email'],
            },
        ),
    ]
