# Generated by Django 6.0.6 on 2026-07-12 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('telephone', models.CharField(blank=True, default='', max_length=40)),
                ('note', models.TextField(blank=True, default='')),
                ('provenance', models.CharField(blank=True, default='', max_length=40)),
                ('cree_le', models.DateTimeField(blank=True, null=True)),
                ('id_compte_legacy', models.CharField(blank=True, default='', max_length=120)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='comptes.organisation')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'db_table': 'clients',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('entrant', 'Entrant'), ('sortant', 'Sortant')], max_length=16)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(default='')),
                ('date', models.DateTimeField()),
                ('montant_restant', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('nom_client_facture', models.CharField(blank=True, default='', max_length=200)),
                ('id_compte_legacy', models.CharField(blank=True, default='', max_length=120)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finances.client')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='comptes.organisation')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'db_table': 'transactions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paye_le', models.DateTimeField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='finances.transaction')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'db_table': 'paiements',
                'ordering': ['paye_le'],
            },
        ),
        migrations.CreateModel(
            name='AliasClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_nom', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias', to='finances.client')),
            ],
            options={
                'verbose_name': 'alias client',
                'verbose_name_plural': 'alias clients',
                'db_table': 'alias_clients',
                'constraints': [models.UniqueConstraint(fields=('client', 'alias_nom'), name='uniq_alias_client_nom')],
            },
        ),
    ]
