# Generated by Django 6.0.6 on 2026-07-12 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_organisation_sync_seq'),
        ('finances', '0003_paiement_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerrouEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ressource_type', models.CharField(choices=[('transaction', 'Transaction'), ('client', 'Client')], max_length=32)),
                ('ressource_id', models.CharField(max_length=128)),
                ('utilisateur_nom', models.CharField(max_length=200)),
                ('expire_le', models.DateTimeField()),
            ],
            options={
                'db_table': 'verrous_edition',
            },
        ),
        migrations.RenameIndex(
            model_name='paiement',
            new_name='paiements_client__0d9f6c_idx',
            old_name='paiements_client_paye_idx',
        ),
        migrations.AddField(
            model_name='client',
            name='modifie_le',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='modifie_le',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='verrouedition',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verrous', to='comptes.organisation'),
        ),
        migrations.AddField(
            model_name='verrouedition',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verrous_edition', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='verrouedition',
            index=models.Index(fields=['expire_le'], name='verrous_edi_expire__0e11c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='verrouedition',
            constraint=models.UniqueConstraint(fields=('organisation', 'ressource_type', 'ressource_id'), name='uniq_verrou_ressource_org'),
        ),
    ]
