# Generated by Django 6.0.6 on 2026-07-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_verrouedition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-cree_le', 'nom'], 'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
    ]
