# Generated by Django 6.0.6 on 2026-07-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_alter_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='categorie_produit',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
