# Generated by Django 6.0.6 on 2026-07-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_note_client_categorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-epinglee', '-modifie_le', '-cree_le'], 'verbose_name': 'note', 'verbose_name_plural': 'notes'},
        ),
        migrations.AddField(
            model_name='note',
            name='archivee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='epinglee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='rappel_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
