# Generated by Django 6.0.6 on 2026-08-16 04:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_transaction_lignes_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'sondages',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='SondageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=160)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'sondage_options',
                'ordering': ['ordre', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SondageReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repondu_le', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'sondage_reponses',
            },
        ),
        migrations.AddField(
            model_name='sondage',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sondages_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sondageoption',
            name='sondage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='finances.sondage'),
        ),
        migrations.AddField(
            model_name='sondagereponse',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='finances.sondageoption'),
        ),
        migrations.AddField(
            model_name='sondagereponse',
            name='sondage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='finances.sondage'),
        ),
        migrations.AddField(
            model_name='sondagereponse',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_sondages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sondagereponse',
            index=models.Index(fields=['sondage', 'option'], name='sondage_rep_sondage_92dfc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='sondagereponse',
            constraint=models.UniqueConstraint(fields=('sondage', 'utilisateur'), name='uniq_reponse_sondage_utilisateur'),
        ),
    ]
